### ISSUE TITLE
Using class for styling elements

### ISSUE THREAD

**Issue by cyouh95** [elevent23/prj-rev-bwfs-dasmoto#2]
Alternatively, you could add a `class` attribute to your `span` elements and use that as the selector to style these price texts. That way, in case you want to use the `span` tag for something else later, they won't all automatically be styled blue already.

HTML:
```html
<span class="price">Starting at $3.00 / brush.</span>
```

CSS:
```css
.price {
  color:blue;
  font-weight:bold;
  font-family:Helvetica;
}
```

https://github.com/elevent23/prj-rev-bwfs-dasmoto/blob/master/Dasmato's%20Arts%20and%20Crafts/index.html#L20
https://github.com/elevent23/prj-rev-bwfs-dasmoto/blob/master/Dasmato's%20Arts%20and%20Crafts/Resources/style.css#L10-L14
