### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [elevent23/prj-rev-bwfs-dasmoto#3]
If you want to specify a style property for all the elements, you could use `body` as the selector, since all its children elements would then automatically inherit the property. For example:

```css
body {
  font-family:Helvetica;
}
```
