### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [elevent23/prj-rev-bwfs-dasmoto#4]
Alternatively, you could use `h2` as the selector for specifying the shared properties among the 3 headings:

```css
h2 {
  color:white;
  font-family:Helvetica;
  font-weight:bold;
  font-size:32px;
}
```

https://github.com/elevent23/prj-rev-bwfs-dasmoto/blob/master/Dasmato's%20Arts%20and%20Crafts/Resources/style.css#L15-L36
